name: Simple Coverage Diff

branding:
  icon: umbrella
  color: green

description: Comment coverage diff to PR.

inputs:
  head-summary-json:
    description: Path of the json-summary file to analyze.
    required: false
    default: coverage/coverage-summary.json
  base-summary-json:
    description: Path of the json-summary file to compare.
    required: true
  body-header:
    description: Comment body header part.
    default: ""
    required: false
  body-footer:
    description: Comment body footer part.
    default: ""
    required: false
  github-token:
    description: A GitHub token to write comments.
    required: true
    default: ${{ github.token }}

runs:
  using: node16
  main: dist/index.js
