name: release

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
  push:
    tags:
      - v*

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run clean
      - run: npm run build
      - uses: int128/release-typescript-action@v1
