name: Action test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: npm install, build, and test
        run: |
          npm ci
          npm run clean
          npm run build
          npm test
        env:
          CI: true

      - name: Test action.yml
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary.json
          head-summary-json: coverage/coverage-summary.json
