name: Action test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: |
          npm run lint
          npm run compile
          npm run clean
          npm run build

      - name: Generate coverage json-summary files for action test
        run: |
          npm run test:base
          cp coverage/coverage-summary.json coverage/coverage-summary-base.json
          npm run test:head
        env:
          CI: true

      - name: Test action.yaml (No changes)
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary-base.json
          head-summary-json: coverage/coverage-summary-base.json

      - name: Test action.yaml (Increase)
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary-base.json
          head-summary-json: coverage/coverage-summary.json
          check-criteria: lines
          coverage-threshold: 80

      - name: Test action.yaml (Header and Footer)
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary-base.json
          head-summary-json: coverage/coverage-summary-base.json
          body-header: |
            ## Hi
          body-footer: |
            ---
            [Link to GitHub](https://github.com)
