name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build
          npm test
        env:
          CI: true
      - name: Test action.yml
        uses: ./action.yml
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-filename: coverage/coverage-summary.json
          base-summary-filename: coverage/coverage-summary.json
